version: '3.2'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  dbdata:
