default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: btfy_development

test:
  <<: *default
  database: btfy_test

production:
  <<: *default
  database: btfy_production
  username: btfy
  password: <%= ENV['BTFY_DATABASE_PASSWORD'] %>
